api:
  key: ""
  secret: ""

oauth:
  token: ""
  secret: ""

download:
  path: "path.to/folder"

spring:
  rabbitmq:
    addresses: ""

listeners:
  download:
    enabled: true
  context:
    enabled: false
  photosets:
    enabled: true
    add:
      enabled: true

queue:
  flickr:
    photosets:
      photos: "queue.flickr.photosets.photos"
      add: "queue.flickr.photosets.add"
    download: "queue.flickr.download"
    context: "queue.flickr.context"

logging:
  level:
    com:
      tbilou: DEBUG