name: Test tags

on:
  push:
    branches:
      - master
  
jobs:
  app-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v4
      
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 1.0.0 # Optional fallback tag to use when no tag can be found

    - name: version
      run: echo ${{ steps.previoustag.outputs.tag }}
