name: Test tags

on:
  push:
    branches:
      - master
  
jobs:
  app-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v4
    
    # Creates a tag      
    # - name: Bump version and push tag
    #   id: tag_version
    #   uses: mathieudutour/github-tag-action@v6.2
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     custom_tag: 42

    - name: 'Get latest tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 1.0.0 # Optional fallback tag to use when no tag can be found

    - name: version
      run: echo ${{ steps.previoustag.outputs.tag }}
